# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 22 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkin:
  #定义名为 checkin 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest
    #将作业配置为在最新版本的 Ubuntu Linux 运行器上运行
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - uses: actions/checkout@v2

    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Checkin
      run: |
        python3 ./main.py
